---
variables:
  DOCKER_IMAGE_NAME: lansible/buaut

include:
  - template: Container-Scanning.gitlab-ci.yml
  - remote: https://raw.githubusercontent.com/LANsible/gitlab-includes/master/docker-login.yml
  - remote: https://raw.githubusercontent.com/LANsible/gitlab-includes/master/docker-build.yml
  - remote: https://raw.githubusercontent.com/LANsible/gitlab-includes/master/sast-cis-benchmark.yml

stages:
  - lint
  - build
  - test
  - push
  - manifest

# TODO: improve test phase
test:
  stage: test
  tags:
  - local  # do not run on shared runner
  - docker
  script:
    # Run image to test
    - docker run -t --tmpfs /tmp:exec ${CI_REGISTRY_IMAGE}:${CI_COMMIT_REF_SLUG}-amd64
